#pragma once

#include <string>
#include <unordered_map>
#include <vector>

namespace Core::Utils
{
enum class VehicleType
{
	Aircraft,
	Helicopter,
	Bike,
	Convertible,
	Industrial,
	Lowrider,
	OffRoad,
	PublicService,
	Saloon,
	SportsCar,
	StationWagon,
	Boat,
	Trailer,
	Unique,
	RC
};

struct VehicleInfo
{
	int modelId;
	std::string name;
};

inline const std::unordered_map<VehicleType, std::vector<VehicleInfo>>
	VEHICLE_LIST = {
		{ VehicleType::Aircraft,
			{ VehicleInfo { 511, "Beagle" }, VehicleInfo { 512, "Cropduster" },
				VehicleInfo { 593, "Dodo" }, VehicleInfo { 553, "Nevada" },
				VehicleInfo { 476, "Rustler" }, VehicleInfo { 519, "Shamal" },
				VehicleInfo { 460, "Skimmer" },
				VehicleInfo { 513, "Stuntplane" } } },
		{ VehicleType::Helicopter,
			{ VehicleInfo { 548, "Cargobob" }, VehicleInfo { 417, "Leviathan" },
				VehicleInfo { 487, "Maverick" },
				VehicleInfo { 488, "News Maverick" },
				VehicleInfo { 497, "Police Maverick" },
				VehicleInfo { 563, "Raindance" },
				VehicleInfo { 447, "Seasparrow" },
				VehicleInfo { 469, "Sparrow" } } },
		{ VehicleType::Bike,
			{ VehicleInfo { 581, "BF-400" }, VehicleInfo { 509, "Bike" },
				VehicleInfo { 481, "BMX" }, VehicleInfo { 462, "Faggio" },
				VehicleInfo { 521, "FCR-900" }, VehicleInfo { 463, "Freeway" },
				VehicleInfo { 510, "Mountain Bike" },
				VehicleInfo { 522, "NRG-500" }, VehicleInfo { 461, "PCJ-600" },
				VehicleInfo { 448, "Pizzaboy" }, VehicleInfo { 471, "Quad" },
				VehicleInfo { 468, "Sanchez" },
				VehicleInfo { 586, "Wayfarer" } } },
		{ VehicleType::Convertible,
			{ VehicleInfo { 480, "Comet" }, VehicleInfo { 533, "Feltzer" },
				VehicleInfo { 439, "Stallion" },
				VehicleInfo { 555, "Windsor" } } },
		{ VehicleType::Industrial,
			{ VehicleInfo { 499, "Benson" }, VehicleInfo { 422, "Bobcat" },
				VehicleInfo { 482, "Burrito" }, VehicleInfo { 498, "Boxville" },
				VehicleInfo { 609, "Boxburg" },
				VehicleInfo { 524, "Cement Truck" },
				VehicleInfo { 578, "DFT-30" }, VehicleInfo { 455, "Flatbed" },
				VehicleInfo { 403, "Linerunner" }, VehicleInfo { 414, "Mule" },
				VehicleInfo { 582, "Newsvan" }, VehicleInfo { 443, "Packer" },
				VehicleInfo { 514, "Petrol Tanker" },
				VehicleInfo { 413, "Pony" }, VehicleInfo { 515, "Roadtrain" },
				VehicleInfo { 440, "Rumpo" }, VehicleInfo { 543, "Sadler" },
				VehicleInfo { 605, "Sadler Shit" },
				VehicleInfo { 459, "Topfun" }, VehicleInfo { 531, "Tractor" },
				VehicleInfo { 408, "Trashmaster" },
				VehicleInfo { 552, "Utility Van" },
				VehicleInfo { 478, "Walton" }, VehicleInfo { 456, "Yankee" },
				VehicleInfo { 554, "Yosemite" } } },
		{ VehicleType::Lowrider,
			{ VehicleInfo { 536, "Blade" }, VehicleInfo { 575, "Broadway" },
				VehicleInfo { 534, "Remington" },
				VehicleInfo { 567, "Savanna" }, VehicleInfo { 535, "Slamvan" },
				VehicleInfo { 566, "Tahoma" }, VehicleInfo { 576, "Tornado" },
				VehicleInfo { 412, "Voodoo" } } },
		{ VehicleType::OffRoad,
			{ VehicleInfo { 568, "Bandito" },
				VehicleInfo { 424, "BF Injection" },
				VehicleInfo { 573, "Dune" }, VehicleInfo { 579, "Huntley" },
				VehicleInfo { 400, "Landstalker" }, VehicleInfo { 500, "Mesa" },
				VehicleInfo { 444, "Monster" },
				VehicleInfo { 556, "Monster A" },
				VehicleInfo { 557, "Monster B" },
				VehicleInfo { 470, "Patriot" },
				VehicleInfo { 489, "Rancher A" },
				VehicleInfo { 505, "Rancher B" },
				VehicleInfo { 495, "Sandking" } } },
		{ VehicleType::PublicService,
			{ VehicleInfo { 416, "Ambulance" }, VehicleInfo { 433, "Barracks" },
				VehicleInfo { 431, "Bus" }, VehicleInfo { 438, "Cabbie" },
				VehicleInfo { 437, "Coach" },
				VehicleInfo { 523, "Cop Bike (HPV-1000)" },
				VehicleInfo { 427, "Enforcer" },
				VehicleInfo { 490, "FBI Rancher" },
				VehicleInfo { 528, "FBI Truck" },
				VehicleInfo { 407, "Firetruck" },
				VehicleInfo { 544, "Firetruck LA" },
				VehicleInfo { 596, "Police Car (LSPD)" },
				VehicleInfo { 598, "Police Car (LVPD)" },
				VehicleInfo { 597, "Police Car (SFPD)" },
				VehicleInfo { 599, "Ranger" }, VehicleInfo { 601, "S.W.A.T" },
				VehicleInfo { 420, "Taxi" } } },
		{ VehicleType::Saloon,
			{ VehicleInfo { 445, "Admiral" },
				VehicleInfo { 504, "Bloodring Banger" },
				VehicleInfo { 401, "Bravura" },
				VehicleInfo { 518, "Buccaneer" },
				VehicleInfo { 527, "Cadrona" }, VehicleInfo { 542, "Clover" },
				VehicleInfo { 507, "Elegant" }, VehicleInfo { 562, "Elegy" },
				VehicleInfo { 585, "Emperor" },
				VehicleInfo { 419, "Esperanto" },
				VehicleInfo { 526, "Fortune" },
				VehicleInfo { 604, "Glendale Shit" },
				VehicleInfo { 466, "Glendale" },
				VehicleInfo { 492, "Greenwood" }, VehicleInfo { 474, "Hermes" },
				VehicleInfo { 546, "Intruder" },
				VehicleInfo { 517, "Majestic" }, VehicleInfo { 410, "Manana" },
				VehicleInfo { 551, "Merit" }, VehicleInfo { 516, "Nebula" },
				VehicleInfo { 467, "Oceanic" }, VehicleInfo { 600, "Picador" },
				VehicleInfo { 426, "Premier" }, VehicleInfo { 436, "Previon" },
				VehicleInfo { 547, "Primo" }, VehicleInfo { 405, "Sentinel" },
				VehicleInfo { 580, "Stafford" }, VehicleInfo { 560, "Sultan" },
				VehicleInfo { 550, "Sunrise" }, VehicleInfo { 549, "Tampa" },
				VehicleInfo { 540, "Vincent" }, VehicleInfo { 491, "Virgo" },
				VehicleInfo { 529, "Willard" },
				VehicleInfo { 421, "Washington" } } },
		{ VehicleType::SportsCar,
			{ VehicleInfo { 602, "Alpha" }, VehicleInfo { 429, "Banshee" },
				VehicleInfo { 496, "Blista Compact" },
				VehicleInfo { 402, "Buffalo" }, VehicleInfo { 541, "Bullet" },
				VehicleInfo { 415, "Cheetah" }, VehicleInfo { 589, "Club" },
				VehicleInfo { 587, "Euros" }, VehicleInfo { 565, "Flash" },
				VehicleInfo { 494, "Hotring Racer" },
				VehicleInfo { 502, "Hotring Racer A" },
				VehicleInfo { 503, "Hotring Racer B" },
				VehicleInfo { 411, "Infernus" }, VehicleInfo { 559, "Jester" },
				VehicleInfo { 603, "Phoenix" }, VehicleInfo { 475, "Sabre" },
				VehicleInfo { 506, "Super GT" }, VehicleInfo { 451, "Turismo" },
				VehicleInfo { 558, "Uranus" },
				VehicleInfo { 477, "ZR-350" } } },
		{ VehicleType::StationWagon,
			{ VehicleInfo { 418, "Moonbeam" }, VehicleInfo { 404, "Perenniel" },
				VehicleInfo { 479, "Regina" }, VehicleInfo { 458, "Solair" },
				VehicleInfo { 561, "Stratum" } } },
		{ VehicleType::Boat,
			{ VehicleInfo { 472, "Coastguard" }, VehicleInfo { 473, "Dinghy" },
				VehicleInfo { 493, "Jetmax" }, VehicleInfo { 595, "Launch" },
				VehicleInfo { 484, "Marquis" }, VehicleInfo { 430, "Predator" },
				VehicleInfo { 453, "Reefer" }, VehicleInfo { 452, "Speeder" },
				VehicleInfo { 446, "Squallo" },
				VehicleInfo { 454, "Tropic" } } },
		{ VehicleType::Trailer,
			{ VehicleInfo { 435, "Article Trailer" },
				VehicleInfo { 450, "Article Trailer 2" },
				VehicleInfo { 591, "Article Trailer 3" },
				VehicleInfo { 606, "Baggage Trailer A" },
				VehicleInfo { 607, "Baggage Trailer B" },
				VehicleInfo { 610, "Farm Trailer" },
				VehicleInfo { 569, "Freight Flat Trailer (Train)" },
				VehicleInfo { 590, "Freight Box Trailer (Train)" },
				VehicleInfo { 584, "Petrol Trailer" },
				VehicleInfo { 570, "Streak Trailer (Train)" },
				VehicleInfo { 608, "Stairs Trailer" },
				VehicleInfo { 611, "Utility Trailer" } } },
		{ VehicleType::Unique,
			{ VehicleInfo { 485, "Baggage" },
				VehicleInfo { 537, "Brownstreak (Train)" },
				VehicleInfo { 457, "Caddy" }, VehicleInfo { 483, "Camper" },
				VehicleInfo { 508, "Camper A" },
				VehicleInfo { 532, "Combine Harvester" },
				VehicleInfo { 486, "Dozer" }, VehicleInfo { 406, "Dumper" },
				VehicleInfo { 530, "Forklift" },
				VehicleInfo { 538, "Freight (Train)" },
				VehicleInfo { 434, "Hotknife" }, VehicleInfo { 545, "Hustler" },
				VehicleInfo { 588, "Hotdog" }, VehicleInfo { 571, "Kart" },
				VehicleInfo { 572, "Mower" }, VehicleInfo { 423, "Mr Whoopee" },
				VehicleInfo { 442, "Romero" }, VehicleInfo { 428, "Securicar" },
				VehicleInfo { 409, "Stretch" }, VehicleInfo { 574, "Sweeper" },
				VehicleInfo { 449, "Tram" }, VehicleInfo { 525, "Towtruck" },
				VehicleInfo { 583, "Tug" }, VehicleInfo { 539, "Vortex" } } },
		{ VehicleType::RC,
			{ VehicleInfo { 441, "RC Bandit" },
				VehicleInfo { 465, "RC Raider" },
				VehicleInfo { 501, "RC Goblin" },
				VehicleInfo { 564, "RC Tiger" },
				VehicleInfo { 594, "RC Cam" } } }
	};
}