// generated by "sampctl package init"
#include <open.mp>

main() 
{
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
	print("Hello, World!");
}
