#pragma once

#define ACCENT_MAIN 0xFF0000FF // SERVER COLOR
#define ACCENT_SECONDARY 0xFFFFFFFF // SERVER COLOR
#define ACCENT_MAIN_E "{FF0000}" // SERVER COLOR Embedded
#define ACCENT_SECONDARY_E "{FFFFFF}" // SERVER COLOR Embedded

#define DIALOG_HEADER_TITLE "" ACCENT_MAIN_E "Oasis " ACCENT_SECONDARY_E " | %s"
#define DIALOG_TABLIST_TITLE_COLOR ACCENT_MAIN_E // Embedded
#define DIALOG_HEADER DIALOG_HEADER_TITLE // embedded
#define DIALOG_TABLIST DIALOG_TABLIST_TITLE_COLOR